Don't refer to more content button if always_true is set (#3461)
* Don't refer to more content button if always_true is set

If you set `always_show: true` on a trip field and it has more than 50 characters there is a javascript error:

    Error: Missing target element "moreContentButton" for "trix-body" controller

This is because the trix field show component only adds the more content button when `always_show` is `false` but the trix controller always refers to that component without checking if it exists first.

I've updated it so that it checks if that target exists before manipulating it.

* check always_show on the controller

---------

Co-authored-by: Paul Bob <paul.ionut.bob@gmail.com>
Co-authored-by: Paul Bob <69730720+Paul-Bob@users.noreply.github.com>